server:
  port: 8099
spring:
  application:
    name: consents
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  # data:
    # mongodb:
      # uri: mongodb://usuario:senha@servidor:27017/SEU_BANCO